name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # 每 5 分鐘（GitHub 排程最小間隔）
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: keep-render-awake
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Warm up & health check
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}   # 請在 Settings → Secrets 設定
        run: |
          set -Eeuo pipefail
          : "${TARGET_URL:?TARGET_URL secret is required}"

          URL="${TARGET_URL}"
          UA="GH-Actions-HealthCheck"

          # 最多嘗試 6 次；遇到暫時性錯誤等一下再試
          for i in {1..6}; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" \
              -A "$UA" -L --connect-timeout 10 --max-time 60 \
              --retry 3 --retry-all-errors \
              "$URL" || echo "000")

            echo "Attempt $i -> HTTP $CODE"

            # 2xx/3xx = 成功
            if [ "$CODE" -ge 200 ] && [ "$CODE" -lt 400 ]; then
              echo "OK"
              exit 0
            fi

            # 冷啟動/暫時性：502/503/504/000 → 等 10 秒重試
            if [ "$CODE" = "502" ] || [ "$CODE" = "503" ] || [ "$CODE" = "504" ] || [ "$CODE" = "000" ]; then
              sleep 10
              continue
            fi

            # 其他狀態碼先等一下再試一次
            sleep 10
          done

          echo "Service unhealthy after retries."
          exit 1
