name: PostgreSQL backup to Google Drive (every 30min)

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (UTC)
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      # --- PostgreSQL conn (Render) ---
      PGHOST:       ${{ secrets.PGHOST }}
      PGPORT:       ${{ secrets.PGPORT }}
      PGDATABASE:   ${{ secrets.PGDATABASE }}
      PGUSER:       ${{ secrets.PGUSER }}
      PGPASSWORD:   ${{ secrets.PGPASSWORD }}
      PGSSLMODE:    require   # Render/雲端DB 常見要求 TLS

      # --- Google Drive via rclone remote "gdrive" ---
      RCLONE_CONF_B64: ${{ secrets.RCLONE_CONF_B64 }}
      GDRIVE_DIR:   ${{ secrets.GDRIVE_DIR }}  # e.g. "gdrive:pg-backups/prod"

    steps:
      - name: Timestamp (Taipei)
        id: ts
        run: echo "STAMP=$(TZ=Asia/Taipei date +'%Y%m%d_%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Install rclone
        run: |
          set -eux
          curl -fsSL https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Restore rclone config
        run: |
          set -eux
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF_B64" | base64 -d > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf
          # 驗證 remote 是否存在；若子資料夾不存在不會失敗
          rclone about "$(echo "$GDRIVE_DIR" | cut -d: -f1):"

      - name: Preflight - DB connectivity (dockerized psql 17)
        run: |
          set -eux
          docker run --rm \
            -e PGPASSWORD="$PGPASSWORD" \
            -e PGSSLMODE="$PGSSLMODE" \
            postgres:17 \
            psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c 'SELECT version();'

      - name: Stream dump (dockerized pg_dump 17) -> gzip -> rclone rcat
        run: |
          set -euo pipefail
          FNAME="${PGDATABASE}_${{ steps.ts.outputs.STAMP }}.sql.gz"
          # 用 postgres:17 內的 pg_dump，確保版本相容
          docker run --rm \
            -e PGPASSWORD="$PGPASSWORD" \
            -e PGSSLMODE="$PGSSLMODE" \
            postgres:17 \
            pg_dump -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" \
              --format=plain --no-owner --no-privileges \
          | gzip -9 \
          | rclone rcat -vv "${GDRIVE_DIR}/${FNAME}"

      # （可選）保留 7 天
      # - name: Retention - keep 7d
      #   run: |
      #     set -eux
      #     rclone delete "${GDRIVE_DIR}" --min-age 7d --drive-use-trash=false
      #     rclone rmdirs "${GDRIVE_DIR}" --leave-root
